# Site settings
title: Ryan Hughes
description: Entrepreneur with a passion for tech
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Hughes
user_title: Partner, Chief Innovation Officer @ Oodle
email: ryan@ryanhughes.me
twitter_username: ryanrhughes
github_username:  ryanrhughes

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
